version: '3.3'
services:
  registry-ui:
    image: 'joxit/docker-registry-ui:static'
    depends_on:
      - registry
    ports:
      - '8090:80'
    environment:
      - REGISTRY_URL=http://registry-pozos:5000
      - REGISTRY_TITLE=POZOS
      - DELETE_IMAGES=true
    networks:
      - POZOS
    container_name: frontend-pozos
  registry:
    image: 'registry:2'
    ports:
      - '5001:5000'
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    networks:
      - POZOS
    container_name: registry-pozos
networks:
  POZOS:
